services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - dynamodb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    ports:
      - "8001:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory
